name: Uniswap V3 Fee Tracker

on:
  schedule:
    - cron: '0 20 * * *' # 20:00 UTC (ist 22:00 CEST / 21:00 CET)
  workflow_dispatch: # Ermöglicht manuellen Start

jobs:
  track-fees:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 
        with:
          fetch-depth: 0 # Wichtig für den Commit-Schritt, um die volle Historie zu haben

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run fee tracker script
        env:
          ARBITRUM_RPC: ${{ secrets.ARBITRUM_RPC }}
          POSITION_ID: ${{ secrets.POSITION_ID }}
          WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
        run: python tracker.py

      - name: Commit and push if data changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add fees_history.db # Oder wie auch immer deine Datendatei heißt
          # Prüfen, ob es Änderungen gibt, um leere Commits zu vermeiden
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated fee tracking update via GitHub Action"
            git push
          fi